---
name: step1_destination_hub_lab
description: destination_hub_lab
priority: 1
condition: "true"
actions:
  - "calculation = step1_select_destination_hub_or_lab == 'destination_hub' ? step1_name_of_hf : step1_name_of_lab"